
import {
  LayoutDashboard,
  User,
  CreditCard,
  Settings,
  Package,
  Calendar,
  Receipt,
  Coins,
  FileContract,
  Users,
  LineChart,
  Share2,
  Award,
  MessageSquare,
  FileText,
  PenTool,
  Menu,
} from "lucide-react";

export const Icons = {
  overview: LayoutDashboard,
  profile: User,
  billing: CreditCard,
  subscription: Package,
  settings: Settings,
  bookings: Calendar,
  campaigns: Receipt,
  credits: Coins,
  contracts: FileContract,
  kols: Users,
  analytics: LineChart,
  referrals: Share2,
  rewards: Award,
  applications: FileText,
  community: MessageSquare,
  overview: LayoutDashboard,
  menu: Menu,
};
